---
tools_library: !include tools.yml
common: # settings shared by agent and all tools (can be overwritten by passing explicitly to constructors)
  llm: 'gpt-4'
  fast_llm: 'gpt-3.5-turbo'
  fast_llm_token_limit: 2500
  max_token_length: 4000
tools: # list of all tools available for the agent
  - sql_tool
  - visualizer_tool
  - summarizer_tool
  - expert_tool
  - entertainer_tool
  - pdf_tool
  - clarify_tool
  - chain_tool
  - image_generation_tool
action_plans: # list of all action plans available for the meta agent
  '0':
    name: 'Q&A'
    description: Use this plan to answer questions about recipes, meals, ingredients, and shopping lists.
    actions: # each sublist is 1 action step, i.e. add tools as subitems if you want to execute in parallel
      - - pdf_tool
  '1':
    name: 'Search'
    description: |-
      Use this plan to fetch data about meals, recipes, ingredients, and shopping lists.
    actions:
      - - sql_tool
      - - expert_tool
  '2':
    name: 'Visualize'
    description:  |-
      Sufficient information in chat history, visualize
    actions:
      - - memory
        - sql_tool
      - - visualizer_tool
prompt_message: |-
  Given the chat history and the user question, what action plan would be best to follow?
  Remember to only put out the number of the action plan you want to follow.

  User question: {input}
system_context: |-
  You are an expert planning meals for a busy family
  Your goal is to select the right action plan for the question of the user in the fastest way possible, given the chat history.

  The information that can be gathered are from a database of recipes.
  The database includes information on recipes, cuisines, whether the parents and kids of the family like the recipes, how difficult they are, what ingredients they require, and how long they take to make.

  Follow the below guidelines:
  - Gathering new information takes time, only do it if necessary
  - Only visualize if the user asks for it
  - If the latest user question is referring to information provided in earlier messages, answer with "2", "3", or "4"

  Action plans:
  {action_plans}

  Only reply with the number of the action plan you want to follow and nothing else. For example: "0" or "1" or "2" or "3" or "4"
